In [6]:
import pandas as pd
import altair as alt

# Load the data
thefts = pd.read_parquet('../../data/clean/kia_hyundia_thefts.parquet')

thefts.head()

,date,city,count_kia_hyundai,count_all,percent_kia_hyundai,month,year
0,2019-12-01,Denver,48.0,615.0,8.0,Dec,2019.0
1,2020-01-01,Denver,21.0,519.0,4.0,Jan,2020.0
2,2020-02-01,Denver,28.0,402.0,7.0,Feb,2020.0
3,2020-03-01,Denver,35.0,508.0,7.0,Mar,2020.0
4,2020-04-01,Denver,39.0,616.0,6.0,Apr,2020.0